tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/versions"
tap "universal-ctags/universal-ctags"
brew "automake"
brew "gdbm"
brew "openssl"
brew "readline"
brew "sqlite"
brew "xz"
brew "python"
brew "aws-shell"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bash-git-prompt"
brew "bison"
brew "ccat"
brew "chruby"
brew "colordiff"
brew "ctop"
brew "diff-so-fancy"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "gmp"
brew "go"
brew "gotags"
brew "libtool"
brew "graphviz"
brew "hexcurse"
brew "httpie"
brew "hub"
brew "icdiff"
brew "icu4c"
brew "id3v2"
brew "jenv"
brew "jq"
brew "libffi"
brew "libyaml"
brew "lnav"
brew "mas"
brew "mongodb"
brew "mtr"
brew "mysql"
brew "namebench"
brew "node"
brew "nvm"
brew "parallel"
brew "pkg-config"
brew "prettyping"
brew "pyenv"
brew "ranger"
brew "ripgrep"
brew "ruby-install"
brew "tig"
brew "vim"
brew "yarn"
brew "youtube-dl"
brew "z"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "adobe-acrobat-reader"
cask "adobe-air"
cask "appcleaner"
cask "atext"
cask "bartender"
cask "dash"
cask "docker"
cask "dropbox"
cask "firefox"
cask "flycut"
cask "goofy"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-drive-file-stream"
cask "gpgtools"
cask "grammarly"
cask "grandperspective"
cask "imagealpha"
cask "imageoptim"
cask "itsycal"
cask "java"
cask "jd-gui"
cask "jet"
cask "kap"
cask "keka"
cask "keycastr"
cask "libreoffice"
cask "macvim"
cask "mat"
cask "mongodb-compass"
cask "pandora"
cask "pingplotter"
cask "postman"
cask "robo-3t"
cask "screenflick"
cask "sketch"
cask "skitch"
cask "skype"
cask "slack"
cask "smallpdf"
cask "spectacle"
cask "time-out"
cask "tomighty"
cask "visualvm"
cask "vlc"
cask "whatsapp"
cask "yujitach-menumeters"
cask "zoomus"
mas "GarageBand", id: 682658836
mas "GIF Keyboard", id: 1043270657
mas "Hour", id: 569089415
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "iPhoto", id: 408981381
mas "Irvue", id: 1039633667
mas "JPEGmini Lite", id: 525742250
mas "Keynote", id: 409183694
mas "NeoOffice", id: 639210716
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Polarr Photo Editor Pro", id: 1058273036
mas "Publisher Master - Graphic Design & Page Layout Creator", id: 998756839
mas "Swift Publisher 5", id: 1058362543
mas "Swipes", id: 1008187030
