tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "caskroom/versions"
tap "caskroom/cask"
brew "automake"
brew "aws-shell"
brew "gdbm"
brew "openssl"
brew "sqlite"
brew "xz"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bash-git-prompt"
brew "ccat"
brew "chruby"
brew "colordiff"
brew "ctags"
brew "ctop"
brew "git"
brew "ffmpeg"
brew "gmp"
brew "go"
brew "gotags"
brew "httpie"
brew "hub"
brew "icdiff"
brew "icu4c"
brew "id3v2"
brew "jenv"
brew "jq"
brew "libtool"
brew "libyaml"
brew "lnav"
brew "mas"
brew "mtr"
brew "mysql"
brew "pkg-config"
brew "prettyping"
brew "pyenv"
brew "python"
brew "ranger"
brew "ripgrep"
brew "ruby"
brew "ruby-install"
brew "tig"
brew "vim"
brew "yarn"
brew "youtube-dl"
cask "adobe-air"
cask "appcleaner"
cask "atext"
cask "bartender"
cask "dash"
cask "docker"
cask "dropbox"
cask "firefox"
cask "flycut"
cask "google-chrome"
cask "gpgtools"
cask "grammarly"
cask "grandperspective"
cask "imagealpha"
cask "imageoptim"
cask "itsycal"
cask "java"
cask "jd-gui"
cask "jet"
cask "kap"
cask "keka"
cask "keycastr"
cask "macvim"
cask "mat"
cask "pandora"
cask "pingplotter"
cask "postman"
cask "quip"
cask "screenflick"
cask "sketch"
cask "skitch"
cask "skype"
cask "slack"
cask "spectacle"
cask "time-out"
cask "visualvm"
cask "vlc"
cask "whatsapp"
cask "yujitach-menumeters"
cask "zoomus"
mas "GarageBand", id: 682658836
mas "GIFHunter", id: 1031163338
mas "Hour", id: 569089415
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "iPhoto", id: 408981381
mas "Irvue", id: 1039633667
mas "JPEGmini Lite", id: 525742250
mas "Keynote", id: 409183694
mas "Logitech Camera Settings", id: 638332853
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Polarr Photo Editor", id: 1058273036
mas "Xcode", id: 497799835
