tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "lindell/multi-gitter"
tap "moncho/dry"
tap "tilt-dev/tap"
tap "universal-ctags/universal-ctags"
tap "yt-dlp/taps"
brew "antigen"
brew "xz"
brew "automake"
brew "gmp"
brew "libtool"
brew "libyaml"
brew "openssl@3"
brew "readline"
brew "asdf"
brew "gdbm"
brew "openssl@1.1"
brew "sqlite"
brew "python@3.10"
brew "aws-shell"
brew "awscli"
brew "bat"
brew "bottom"
brew "pkg-config"
brew "colordiff"
brew "ctop"
brew "dive"
brew "dog"
brew "duf"
brew "dust"
brew "exa"
brew "exiftool"
brew "fd"
brew "icu4c"
brew "ffmpeg"
brew "node"
brew "fx"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gitbatch"
brew "gitui"
brew "glances"
brew "pinentry"
brew "gnupg"
brew "gotags"
brew "gping"
brew "graphviz"
brew "gron"
brew "hexcurse"
brew "hexyl"
brew "ncurses"
brew "htop"
brew "hub"
brew "icdiff"
brew "id3v2"
brew "jless"
brew "jq"
brew "k9s"
brew "kind"
brew "kubernetes-cli"
brew "lf"
brew "libffi"
brew "lnav"
brew "mas"
brew "mtr"
brew "mycli"
brew "mysql"
brew "ncdu"
brew "nmap"
brew "parallel"
brew "pinentry-mac"
brew "pnpm"
brew "prettyping"
brew "procs"
brew "python@3.8"
brew "python@3.9"
brew "ranger"
brew "ripgrep"
brew "s3cmd"
brew "sd"
brew "starship"
brew "switchaudio-osx"
brew "tealdeer"
brew "tig"
brew "tokei"
brew "topgrade"
brew "tre-command"
brew "wget"
brew "xh"
brew "youtube-dl"
brew "zenith"
brew "zoxide"
brew "zsh"
brew "lindell/multi-gitter/multi-gitter"
brew "moncho/dry/dry"
brew "tilt-dev/tap/tilt"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "yt-dlp/taps/yt-dlp"
cask "1password-cli"
cask "adobe-acrobat-reader"
cask "amazon-chime"
cask "appcleaner"
cask "authy"
cask "bartender"
cask "cleanshot"
cask "datweatherdoe"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-roboto"
cask "font-smoothing-adjuster"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-drive"
cask "google-earth-pro"
cask "gotomeeting"
cask "grandperspective"
cask "handbrake"
cask "iina"
cask "imageoptim"
cask "itsycal"
cask "joinme"
cask "karabiner-elements"
cask "keka"
cask "keycastr"
cask "latest"
cask "macvim"
cask "messenger"
cask "microsoft-edge"
cask "microsoft-teams"
cask "mmhmm"
cask "modern-csv"
cask "pingplotter"
cask "prefs-editor"
cask "quip"
cask "quitter"
cask "raycast"
cask "screenflick"
cask "send-to-kindle"
cask "signal"
cask "skype"
cask "slack"
cask "spotify"
cask "stats"
cask "steam"
cask "ticktick"
cask "time-out"
cask "tripmode"
cask "vlc"
cask "webex"
cask "whatsapp"
cask "yubico-yubikey-manager"
cask "zoom"
mas "Focus Window", id: 1444457097
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "Hand Mirror", id: 1502839586
mas "Horo", id: 1437226581
mas "Hour", id: 569089415
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Kindle Classic", id: 405399194
mas "LanguageTool", id: 1534275760
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PDF Squeezer 3", id: 504700302
mas "Pixelmator Pro", id: 1289583905
mas "Polarr Photo Editor", id: 1058273036
mas "Publisher Master", id: 998756839
mas "Recasto", id: 1144192021
mas "Swift Publisher 5", id: 1058362543
mas "UPDF", id: 1619925971
mas "Webcam Settings", id: 533696630
